name: Deployment
on: [push]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      - run: |
              chmod +x './entrypoint.sh'
              ./entrypoint.sh ${{ secrets.GITHUB_TOKEN }}


