name: Deployment
on: [push]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      - run: |
              chmod +x './entrypoint.sh'
              DATA="$(printf '{"tag_name":"v%s",' $VERSION)"
              DATA="${DATA} $(printf '"target_commitish":"master",')"
              DATA="${DATA} $(printf '"name":"v%s",' $VERSION)"
              DATA="${DATA} $(printf '"body":"Automated release based on keyword: %s",' "$*")"
              DATA="${DATA} $(printf '"draft":false, "prerelease":false}')"
              URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/releases?access_token=${GITHUB_TOKEN}"
              echo $DATA | http POST $URL | jq .
              ./entrypoint.sh ${{ secrets.GITHUB_TOKEN }}


